name: CI
on:
  push:
    branches: [main]
  pull_request: {}
permissions:
  contents: read
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.22'
      - run: go vet ./...
      - run: go test ./...
      - run: go build -o /tmp/memoria ./cmd/memoria
